name: lc_reporter
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - cffi=1.14.4
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.10
  - fontconfig=2.13.0
  - freetype=2.10.4
  - glib=2.66.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.0
  - jedi=0.18.0
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.0
  - jupyterlab_pygments=0.1.2
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib-base=3.3.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - notebook=6.1.6
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1i
  - packaging=20.8
  - pandas=1.1.5
  - pandoc=2.11
  - pandocfilters=1.4.3
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.3.3
  - plotly=4.14.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.7.3
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - python=3.8.5
  - python-dateutil=2.8.1
  - pytz=2020.5
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=8.0
  - retrying=1.3.3
  - seaborn=0.11.1
  - send2trash=1.5.0
  - setuptools=51.0.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.33.0
  - terminado=0.9.1
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.11.0
    - aiohttp==3.7.3
    - alabaster==0.7.12
    - async-timeout==3.0.1
    - babel==2.9.0
    - cachetools==4.2.0
    - chardet==3.0.4
    - cycler==0.10.0
    - cython==0.29.21
    - dcor==0.5.2
    - docutils==0.16
    - et-xmlfile==1.0.1
    - fdasrsf==2.2.1
    - findiff==0.8.7
    - fsspec==0.8.5
    - future==0.18.2
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - grpcio==1.34.1
    - gspread==3.6.0
    - h5py==3.1.0
    - hmmlearn==0.2.4
    - httplib2==0.18.1
    - idna==2.10
    - imagesize==1.2.0
    - jdcal==1.4.1
    - joblib==1.0.0
    - kiwisolver==1.3.1
    - llvmlite==0.35.0
    - markdown==3.3.3
    - matplotlib==3.3.3
    - mpldatacursor==0.7.1
    - multidict==5.1.0
    - multimethod==1.4
    - networkx==2.5
    - numba==0.52.0
    - oauth2client==4.1.3
    - oauthlib==3.1.0
    - openpyxl==3.0.5
    - parso==0.8.1
    - patsy==0.5.1
    - pillow==8.1.0
    - pomegranate==0.14.0
    - protobuf==3.14.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pytorch-lightning==1.1.4
    - pyyaml==5.4
    - rdata==0.2.3
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scikit-datasets==0.1.38
    - scikit-fda==0.5
    - scikit-learn==0.24.0
    - scipy==1.6.0
    - snowballstemmer==2.0.0
    - sphinx==3.4.2
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - statsmodels==0.12.1
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - threadpoolctl==2.1.0
    - torch==1.7.1
    - tqdm==4.55.1
    - tsfel==0.1.3
    - tslearn==0.5.1.0
    - typing-extensions==3.7.4.3
    - umap-learn==0.4.6
    - urllib3==1.26.2
    - werkzeug==1.0.1
    - xarray==0.16.2
    - xlrd==2.0.1
    - yarl==1.6.3
